DDBTEAM-830: Added HasCoverMessage and basic config for it
danskernesdigitalebibliotek/ddb-cover-service-importers pull request #105
Opened 2022-03-14 09:19 UTC by cableman

#### Link to ticket

Internal tickets (lots of diffrent tickets).

#### Description

Send information about cover updates to hasCover service.

#### Screenshot of the result

No screenshot.

#### Checklist

- [ ] My code is covered by test cases.
- [ ] My code passes our test (all our tests).
- [ ] My code passes our static analysis suite.
- [ ] My code passes our continuous integration process.

If your code does not pass all the requirements on the checklist you have to add a comment explaining why this change 
should be exempt from the list.

#### Additional comments or questions

No comments.

2022-03-14 16:49 UTC, turegjorup requested changes

2022-03-14 21:52 UTC, cableman commented on src/Service/HasCoverService.php
> +                'auth_bearer' => $this->authenticationService->getAccessToken(),
yes :-D

2022-03-14 21:54 UTC, cableman commented on src/Repository/SearchRepository.php
> +            ->where('s.isType = \''.$type.'\'');
Fixed

2022-03-14 21:55 UTC, cableman commented on .env
> +HAS_COVER_SERVICE_URL=https://ddfhascover-stg.dbc.dk/api/v1/events
In some places they call it DDF has cover as it's a service only used by DDF.

2022-03-14 21:57 UTC, turegjorup approved these changes

2022-06-03 08:30 UTC, cableman commented
Rebase once more with development to match newest code base.

2022-08-12 08:54 UTC, turegjorup approved these changes

2022-08-12 08:54 UTC, turegjorup commented on infrastructure/cover-service-cron-jobs/values.yaml
> +  has_covere:
Shoudn't this be `has_cover`?

2022-08-12 08:54 UTC, turegjorup commented on infrastructure/cover-service-importers/templates/configmap.yaml
> +  APP_HAS_COVER_SERVICE_URL: {{ .Values.app.has_covere.url | quote }}
`has_cover`?

2022-08-12 08:54 UTC, turegjorup commented on infrastructure/cover-service-importers/values.yaml
> +  has_covere:
`has_cover`?

2022-08-12 08:54 UTC, turegjorup commented on infrastructure/cover-service-cron-jobs/templates/configmap.yaml
> +  APP_HAS_COVER_SERVICE_URL: {{ .Values.app.has_covere.url | quote }}
Shouldn't this be `has_cover`?

2022-08-18 08:49 UTC, turegjorup approved these changes

2022-08-19 08:49 UTC, merged