Vendor classes rewrite (metrics)
danskernesdigitalebibliotek/ddb-cover-service-importers pull request #77
Opened 2021-03-10 14:58 UTC by cableman

2021-03-11 09:07 UTC, turegjorup reviewed
I thing we need to rethink having both `AbstractBaseVendorService` & `VendorServiceInterface`. I know why we're doing it. But it seems wrong to me. Once we have the `VendorServiceInterface` and vendors are must inherit from it the `VendorServiceInterface` becomes redundant. We might as well have the interface functions as abstract functions in the `VendorServiceInterface`

I think we solve the problems we are facing simply by having the `VendorCoreService`

2021-03-11 22:06 UTC, turegjorup reviewed
Looks good. But maybe change scope to be "vendor refactor". Then do metrics in a new PR?

2021-03-11 22:10 UTC, cableman commented
Then I think what i'am missing here is moving Exception classes and check-up on the locks across processes

2021-03-13 14:14 UTC, turegjorup requested changes
I like this. I think we are close to it being done. Two things:

**Change requested:** 
`host` and `port` should be configurable in .env in `App\Service\MetricsService`

**Comment/suggestion:**
I don't like having the `getVendorId()` and `getVendorName()` duplicated in all vendor services. I know traits can't have constants but the can reference them. Also consolidating functions in the `VendorCoreService` is a big improvement but we could limit duplication even further by adding this:

`config/services.yaml`:
```
_instanceof:
    App\Service\VendorService\VendorServiceInterface:
        tags: [app.vendor.service]
            calls:
                - setVendorCoreService: [ '@App\Service\VendorService\VendorCoreService' ]
```

`App\Service\VendorService\VendorServiceInterface`:
```
    /**
     * Set the Vendor Core Service
     *
     * @param VendorCoreService $vendorCoreService
     *   The Vendor core service
     */
    public function setVendorCoreService(VendorCoreService $vendorCoreService): void;
```

`App\Service\VendorService\VendorServiceTrait`:
```
    private $vendorCoreService;

    /**
     * {@inheritdoc}
     */
    public function setVendorCoreService(VendorCoreService $vendorCoreService)
    {
        $this->vendorCoreService = $vendorCoreService;
    }

    /**
     * {@inheritdoc}
     */
    public function getVendorId(): int
    {
        return self::VENDOR_ID;
    }

    /**
     * {@inheritdoc}
     */
    public function getVendorName(): string
    {
        return $this->vendorCoreService->getVendorName($this->getVendorId());
    }
```

Then removing the functions from the individual vendor services.

2021-03-13 15:27 UTC, cableman commented on src/Service/MetricsService.php
> +            'port' => 6379,
dohh

2021-03-13 15:30 UTC, cableman commented on src/Service/MetricsService.php
> +            'port' => 6379,
Focus was moved from that class after the talk about doing metrics in another PR :-) will fix

2021-03-15 19:22 UTC, turegjorup approved these changes

2021-03-15 20:07 UTC, merged